function throwError(state, message) {
  throw generateError(state, message);
}