function UnknownErrorException(t,o){var c;_classCallCheck(this,UnknownErrorException);(c=r.call(this,t,"UnknownErrorException")).details=o;return c}